runtime: python39

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*\.html)
    mime_type: text/html
    static_files: \1
    upload: (.*\.html)
    expiration: "1h"

  - url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
    static_files: \1
    upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: \1
    upload: (.*\.js)

service: abdansm-end-fe
